// Code generated by MockGen. DO NOT EDIT.
// Source: repository/starships.go

// Package repository is a generated GoMock package.
package repository

import (
	model "post-example/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIStarship is a mock of IStarship interface.
type MockIStarship struct {
	ctrl     *gomock.Controller
	recorder *MockIStarshipMockRecorder
}

// MockIStarshipMockRecorder is the mock recorder for MockIStarship.
type MockIStarshipMockRecorder struct {
	mock *MockIStarship
}

// NewMockIStarship creates a new mock instance.
func NewMockIStarship(ctrl *gomock.Controller) *MockIStarship {
	mock := &MockIStarship{ctrl: ctrl}
	mock.recorder = &MockIStarshipMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStarship) EXPECT() *MockIStarshipMockRecorder {
	return m.recorder
}

// GetStarships mock base method.
func (m *MockIStarship) GetStarships() (*model.StarshipsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStarships")
	ret0, _ := ret[0].(*model.StarshipsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStarships indicates an expected call of GetStarships.
func (mr *MockIStarshipMockRecorder) GetStarships() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStarships", reflect.TypeOf((*MockIStarship)(nil).GetStarships))
}
